name: Publish Package

on:
  release:
    types: [created]
  push:
    branches: [ "main", "develop" ]
    paths-ignore:
      - 'package.json'

  workflow_dispatch:

jobs:
  setup:
    name: Build and Versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: yarn
      - run: |
          git config --global user.email "gitops@joseescrich.com"
          git config --global user.name "jes"
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            yarn version --new-version "$(node -p "require('./package.json').version")-snapshot.$(date +%Y%m%d%H%M%S)"
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            yarn version --patch
          fi
      - run: yarn build

  publish-github:
    name: Publish to GitHub
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: cp -r ./dist/* .
      - run: cp package.json .
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
      
  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - run: cp -r ./dist/* .
      - run: cp package.json .
      - run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  push-version:
    name: Push Version Change
    runs-on: ubuntu-latest
    needs: [publish-github, publish-npm]
    steps:
      - uses: actions/checkout@v4
      - run: cp package.json .
      - run: |
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}