name: Publish Package

on:
  release:
    types: [created]
  push:
    branches: ['main', 'develop']
    paths-ignore:
      - 'package.json' # Avoid infinite loop caused by version changes pushed during the workflow
  workflow_dispatch:

jobs:
  setup:
    name: Build and Versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: yarn
      - run: |
          git config --global user.email "gitops@joseescrich.com"
          git config --global user.name "jes"
          if [ "${{ github.event.ref_name }}" == "develop" ]; then
            yarn version --new-version "$(node -p "require('./package.json').version")-snapshot.$(date +%Y%m%d%H%M%S)"
          elif [ "${{ github.event.ref_name }}" == "main" ]; then
            yarn version --patch
          fi
      - run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            dist/
            package.json # Include updated package.json in the artifacts

  publish-github:
    name: Publish to GitHub
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      - run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  push-version:
    name: Push Version Change
    runs-on: ubuntu-latest
    needs: [publish-github, publish-npm]
    steps:
      - uses: actions/checkout@v4
      - run: |
          git add package.json
          git commit -m "Update version [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
